apiVersion: v1
kind: Pod
metadata:
  name: multitool-test
  # labels:
  #   app: mvb
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    command: ["/bin/sh", "-c", "sleep infinity"]
