apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: mvb
  ports:
    - protocol: TCP
      port: 8080      # Порт, на котором будет доступен сервис
      targetPort: 80 # Порт, на котором контейнер слушает внутри Pod
  type: ClusterIP